#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB9069B1335700CDC (infra-root@openstack.org)
#
Name     : bandit
Version  : 1.4.0
Release  : 24
URL      : http://tarballs.openstack.org/bandit/bandit-1.4.0.tar.gz
Source0  : http://tarballs.openstack.org/bandit/bandit-1.4.0.tar.gz
Source99 : http://tarballs.openstack.org/bandit/bandit-1.4.0.tar.gz.asc
Summary  : Security oriented static analyser for python code.
Group    : Development/Tools
License  : Apache-2.0
Requires: bandit-bin
Requires: bandit-python
Requires: GitPython
Requires: PyYAML
Requires: six
Requires: stevedore
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Bandit
======
.. image:: http://governance.openstack.org/badges/bandit.svg
:target: http://governance.openstack.org/reference/tags/index.html
:alt: Bandit team and repository tags

%package bin
Summary: bin components for the bandit package.
Group: Binaries

%description bin
bin components for the bandit package.


%package python
Summary: python components for the bandit package.
Group: Default

%description python
python components for the bandit package.


%prep
%setup -q -n bandit-1.4.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1490889560
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 --verbose || :
%install
export SOURCE_DATE_EPOCH=1490889560
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bandit
/usr/bin/bandit-baseline
/usr/bin/bandit-config-generator

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
